### ISSUE TITLE
Support request: HTTP/2, HTTPS and cookies

### ISSUE THREAD

**Issue by xyproto** [bradfitz/http2#38]
Hi,

Thanks for making the http2 package!

This is not a bug report, but a support request.

I'm trying to make [Algernon](https://github.com/xyproto/algernon), a small web server I am writing, allow users to log in by using cookies. This works perfectly fine over HTTP, but does not seem to work over HTTPS+HTTP/2. I don't know enough about HTTP/2 (possibly not about HTTPS either) to be able to pinpoint why this is.

Algernon uses the [permissions2](https://github.com/xyproto/permissions2) package, and here is the relevant source file that deals with cookies: https://github.com/xyproto/permissions2/blob/master/cookies.go

Here is one way to reproduce the issue I am experiencing:

1. Start a local Redis server
2. `go get github.com/xyproto/algernon`
3. `cd $GOPATH/src/github.com/xyproto/algernon`
4. `go build`
5. `./runexample.sh -http2log http2.log`
6. Visit `https://localhost:3000/register`
7. Visit `https://localhost:3000/login`
8. Observe the following browser output:
~~~
bob is now logged in on the server: true
Could not store the username in a cookie!
~~~

I tried reading the relevant source code for the http2 package, as well as the HTTP/2 spec draft, but was none the wiser. Any help in being able to store secure cookies when using HTTP/2 and HTTPS is warmly welcome.

Best regards,
    Alexander F Rødseth

**Comment by jaredfolkins** [comment]
Howdy Alexander,

The offending line is  [here](https://github.com/xyproto/algernon/blob/21f1eb4c844b7ebe95c8441e77bbf8319391aa8e/server.lua#L7).


```lua
--- Debug mode (errors will be shown in the browser)
SetDebug(true)
```
By setting your environment to debug you then force this fork at the DEBUG_MODE logic block found [here](https://github.com/xyproto/algernon/blob/master/handlers.go#L56-L68).

```go
		if DEBUG_MODE {
			// Use a buffered ResponseWriter for delaying the output
			recorder := httptest.NewRecorder()
			// Run the lua script
			if err := runLua(recorder, req, filename, perm, luapool); err != nil {
				errortext := err.Error()
				// If there were errors, display an error page
				prettyError(w, filename, errortext, "lua")
			} else {
				// If things went well, write to the ResponseWriter
				writeRecorder(w, recorder)
			}
		} else {
```

You'll notice that you are now passing to runLua() a httptest.NewRecorder() which is not capable of emulating a HTTP2 ResponseWriter.

Brad and Blake test the HTTP2 server using a custom client currently. An example can be found [here](https://github.com/bradfitz/http2/blob/master/transport_test.go#L41-L88).

For what it is worth, it took me quite a while to track this down because of the embedded debug flag. The lesson here, in my opinion, is to either use an environment variable or cli flag for modifiers such as this that change your program's global behavior.

Anyway, cool project! Keep up the good work.

Cheers,
Jared

**Comment by bradfitz** [comment]
Sorry, this isn't about http2, so closing.  I don't have time to provide tech support about unrelated issues, and especially not in this forum.

**Comment by xyproto** [comment]
@jaredfolkins Thank you so much Jared!

I'll take your advice to heart and use an environment variable and/or CLI flag instead. Nice catch about the httptest Recorder, I had no idea it would not be capable of emulating a HTTP2 ResponseWriter. Thanks again for figuring this one out!

@bradfitz It is about *http2*, since algernon uses the *http2* package.

Notifying developers of projects that use the *http2* package that they might have to use something like [TestTransport](https://github.com/bradfitz/http2/blob/master/transport_test.go#L41-L88) when they need buffered responses, instead of httptest.NewRecorder, sounds to me like it could be a worthwhile use of time.
