### ISSUE TITLE
Exporting Server.handleConn

### ISSUE THREAD

**Issue by soheilhy** [bradfitz/http2#69]
`Server.handleConn` is the minimum required to implement an `http2` server outside `net/http`, say to implement `h2c`:

```go
s := &http.Server{
	Handler: &myHandler{},
}
s2 := &http2.Server{}
for {
	c, err := l.Accept()
	if err != nil {
		if terr, ok := err.(net.Error); ok && terr.Temporary() {
			continue
		}
		return
	}
	go s2.HandleConn(s, c, s.Handler)
}
```

I have another selfish reason for that. I've built a [connection multiplexer](https://github.com/soheilhy/cmux) that sniffs connections to multiplex them. Using that, I can run net/rpc, gRPC, and HTTP1.1 on the same port. However, I can't do that for HTTP2 because I have to wrap the actual connection in a `cmux` connection. So, the "fake" connection is not a `*tls.Conn` and `TLSNextProto` handlers would never be called for HTTP2 flows.

Would you please consider exporting this method?

Just in case, I confirm that using the snippet above I can serve `h2` (i.e., chrome) and gRPC/TLS traffic on the same port.

**Comment by joushou** [comment]
+1 - I would very much like this exposed for the very same reasons (The ability to serve h2 where TLS has already been handled by other mechanisms, and the negotiated protocol has been determined to be h2 or h2-14).

Apart from exposing the ability to start a h2 connection, it would also make it "easier" to have the HTTP server eat accepted net.Conns, rather than having to make a "fake" net.Listener.

**Comment by philips** [comment]
cc @xiang90

**Comment by joushou** [comment]
I have made this change in my fork https://github.com/joushou/http2, although I have not yet submitted a pull request.

My commit also mentions a potentially cleaner way if we want to do something like this in both net/http and http2. Instead of HandleConn, one could have a NewServerConn (or NewH2Conn) that does this magic, and return (serverConn, error). serverConn would then have Serve exposed.
One would then be able to expose Serve on HTTP/1.1 connections, allowing for a similar functionality on both protocols, depending on whether one calls NewH2Conn, NewH2CConn, or NewH1Conn (probably named differently).

**Comment by philips** [comment]
Any update on this @bradfitz or @bmizerany?

**Comment by bradfitz** [comment]
Sorry, I haven't done it yet.

**Comment by bradfitz** [comment]
This repo just moved into the official Go repo.

See https://github.com/bradfitz/http2/blob/master/README for the move details.

File new bugs at: https://github.com/golang/go/issues/new?title=x/net/http2:+

Closing this bug, but please copy it to the main repo if still relevant or desired. Thanks!

**Comment by joushou** [comment]
@bradfitz Will do. Thank you for your effort in providing us HTTP/2.0 support!
