### ISSUE TITLE
[Minor] h2demo broken links - tiled images

### ISSUE THREAD

**Issue by noam1023** [bradfitz/http2#70]
When running h2demo (on my development machine), the links to the http1 version are broken

https://localhost:4430/gophertiles?latency=0

**Comment by bradfitz** [comment]
@noam1023, sorry for the trouble but this repo just moved into the official Go repo. Could you copy this bug report there, so it's under your name instead of mine?

See https://github.com/bradfitz/http2/blob/master/README for the move details.

File the new bug at: https://github.com/golang/go/issues/new?title=x/net/http2:+

Closing this bug, but please copy it to the main repo. Thanks!
