### ISSUE TITLE
Add debugging data in Go Away frames

### ISSUE THREAD

**Issue by alexmgr** [bradfitz/http2#71]
Hi,

I've written an HTTP2 layer which lives above [scapy](https://bitbucket.org/secdev/scapy/wiki/Home).
I'm using https://http2.golang.org/ to do some testing. Thanks a lot for offering that by the way, it's proven really useful.

One thing which would make debugging easier though, was if the reason for failure was sent in the debug_data section of the Go Away frame. You obviously wouldn't want that in prod, but it would be really useful on the testing server.

For example, this is what I get from the server today when screwing up something in the client packet:
```
###[ HTTP2 ]###
  \frames    \
   |###[ HTTP2 Frame Header ]###
   |  length    = 12
   |  type      = SETTINGS
   |  flags     = 
   |  R         = 0L
   |  stream    = 0L
   |###[ HTTP2 SETTINGS Frame ]###
   |     \settings  \
   |      |###[ HTTP2 Setting ]###
   |      |  id        = SETTINGS_MAX_FRAME_SIZE
   |      |  value     = 1048576
   |      |###[ HTTP2 Setting ]###
   |      |  id        = SETTINGS_MAX_CONCURRENT_STREAMS
   |      |  value     = 250
# Send something unexpected
###[ HTTP2 ]###
  \frames    \
   |###[ HTTP2 Frame Header ]###
   |  length    = 8
   |  type      = GOAWAY
   |  flags     = 
   |  R         = 0L
   |  stream    = 0L
   |###[ HTTP2 GOAWAY Frame ]###
   |     last_stream= 0
   |     error_code= PROTOCOL_ERROR
   |     debug_data= ''
```

Just an idea,
Thanks,
Alex

**Comment by bradfitz** [comment]
@alexmgr, this is a good suggestion. We can do this for the test server. But this repo just moved into the official Go repo. Could you copy this bug report there, so it's under your name instead of mine?

See https://github.com/bradfitz/http2/blob/master/README for the move details.

File the new bug at: https://github.com/golang/go/issues/new?title=x/net/http2:+

Closing this bug, but please copy it to the main repo. Thanks!
